# Copyright 2017 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

module Google
  module Sql
    module Data
      # A class to manage data for settings for instance.
      class InstanceSettings
        include Comparable

        attr_reader :ip_configuration
        attr_reader :tier

        def to_json(_arg = nil)
          {
            'ipConfiguration' => ip_configuration,
            'tier' => tier
          }.reject { |_k, v| v.nil? }.to_json
        end

        def to_s
          {
            ip_configuration: ip_configuration.to_s,
            tier: tier.to_s
          }.map { |k, v| "#{k}: #{v}" }.join(', ')
        end

        def ==(other)
          return false unless other.is_a? InstanceSettings
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            return false if compare[:self] != compare[:other]
          end
          true
        end

        def <=>(other)
          return false unless other.is_a? InstanceSettings
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            result = compare[:self] <=> compare[:other]
            return result unless result.zero?
          end
          0
        end

        def inspect
          to_json
        end

        private

        def compare_fields(other)
          [
            { self: ip_configuration, other: other.ip_configuration },
            { self: tier, other: other.tier }
          ]
        end
      end

      # Manages a InstanceSettings nested object
      # Data is coming from the GCP API
      class InstanceSettingsApi < InstanceSettings
        def initialize(args)
          @ip_configuration = Google::Sql::Property::InstancIpConfigu.api_parse(
            args['ipConfiguration']
          )
          @tier = Google::Sql::Property::String.api_parse(args['tier'])
        end
      end

      # Manages a InstanceSettings nested object
      # Data is coming from the Chef catalog
      class InstanceSettingsCatalog < InstanceSettings
        def initialize(args)
          @ip_configuration =
            Google::Sql::Property::InstancIpConfigu.catalog_parse(
              args[:ip_configuration]
            )
          @tier = Google::Sql::Property::String.catalog_parse(args[:tier])
        end
      end
    end

    module Property
      # A class to manage input to settings for instance.
      class InstanceSettings
        def self.coerce
          ->(x) { ::Google::Sql::Property::InstanceSettings.catalog_parse(x) }
        end

        # Used for parsing Chef catalog
        def self.catalog_parse(value)
          return if value.nil?
          return value if value.is_a? Data::InstanceSettings
          Data::InstanceSettingsCatalog.new(value)
        end

        # Used for parsing GCP API responses
        def self.api_parse(value)
          return if value.nil?
          return value if value.is_a? Data::InstanceSettings
          Data::InstanceSettingsApi.new(value)
        end
      end
    end
  end
end
